# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'art.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ArtWindow(object):
    def setupUi(self, ArtWindow):
        ArtWindow.setObjectName("ArtWindow")
        ArtWindow.setFixedSize(485, 435)
        self.centralwidget = QtWidgets.QWidget(ArtWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_file = QtWidgets.QFrame(self.centralwidget)
        self.frame_file.setGeometry(QtCore.QRect(20, 10, 441, 111))
        self.frame_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file.setObjectName("frame_file")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_file)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 421, 80))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_input)
        self.lineEdit_output = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_output)
        self.pbt_input = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_input.setObjectName("pbt_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pbt_input)
        self.pbt_output = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_output.setObjectName("pbt_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pbt_output)
        self.frame_plot = QtWidgets.QFrame(self.centralwidget)
        self.frame_plot.setGeometry(QtCore.QRect(230, 120, 231, 41))
        self.frame_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot.setObjectName("frame_plot")
        self.pbt_plot = QtWidgets.QPushButton(self.frame_plot)
        self.pbt_plot.setGeometry(QtCore.QRect(130, 0, 93, 28))
        self.pbt_plot.setObjectName("pbt_plot")
        self.pbt_clear = QtWidgets.QPushButton(self.frame_plot)
        self.pbt_clear.setGeometry(QtCore.QRect(0, 0, 93, 28))
        self.pbt_clear.setObjectName("pbt_clear")
        self.line_h1 = QtWidgets.QFrame(self.centralwidget)
        self.line_h1.setGeometry(QtCore.QRect(20, 153, 441, 20))
        self.line_h1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h1.setObjectName("line_h1")
        self.label_des = QtWidgets.QLabel(self.centralwidget)
        self.label_des.setGeometry(QtCore.QRect(30, 170, 121, 21))
        self.label_des.setObjectName("label_des")
        self.textEdit_des = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_des.setGeometry(QtCore.QRect(20, 200, 441, 111))
        self.textEdit_des.setObjectName("textEdit_des")
        ArtWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ArtWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        ArtWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ArtWindow)
        self.statusbar.setObjectName("statusbar")
        ArtWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(ArtWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(ArtWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionHTC_Homepage = QtWidgets.QAction(ArtWindow)
        self.actionHTC_Homepage.setObjectName("actionHTC_Homepage")
        self.actionstyle_requirement = QtWidgets.QAction(ArtWindow)
        self.actionstyle_requirement.setObjectName("actionstyle_requirement")
        self.menufile.addAction(self.actionopen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionexit)
        self.menuhelp.addAction(self.actionHTC_Homepage)
        self.menuhelp.addSeparator()
        self.menuhelp.addAction(self.actionstyle_requirement)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(ArtWindow)
        QtCore.QMetaObject.connectSlotsByName(ArtWindow)

    def retranslateUi(self, ArtWindow):
        _translate = QtCore.QCoreApplication.translate
        ArtWindow.setWindowTitle(_translate("ArtWindow", "plot: average running time"))
        self.pbt_input.setText(_translate("ArtWindow", "Input:"))
        self.pbt_output.setText(_translate("ArtWindow", "Output:"))
        self.pbt_plot.setText(_translate("ArtWindow", "plot"))
        self.pbt_clear.setText(_translate("ArtWindow", "clear"))
        self.label_des.setText(_translate("ArtWindow", "Descriptions:"))
        self.menufile.setTitle(_translate("ArtWindow", "File"))
        self.menuhelp.setTitle(_translate("ArtWindow", "Help"))
        self.actionopen.setText(_translate("ArtWindow", "open"))
        self.actionexit.setText(_translate("ArtWindow", "exit"))
        self.actionHTC_Homepage.setText(_translate("ArtWindow", "HTC Homepage"))
        self.actionstyle_requirement.setText(_translate("ArtWindow", "style requirements"))
