# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CcWindow(object):
    def setupUi(self, CcWindow):
        CcWindow.setObjectName("CcWindow")
        CcWindow.setFixedSize(485, 455)
        self.centralwidget = QtWidgets.QWidget(CcWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_file = QtWidgets.QFrame(self.centralwidget)
        self.frame_file.setGeometry(QtCore.QRect(20, 10, 441, 131))
        self.frame_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file.setObjectName("frame_file")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_file)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 421, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_input)
        self.lineEdit_output = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_output)
        self.pbt_input = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_input.setObjectName("pbt_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pbt_input)
        self.pbt_output = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_output.setObjectName("pbt_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pbt_output)
        self.label_classifier = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_classifier.setObjectName("label_classifier")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_classifier)
        self.lineEdit_classifier = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_classifier.setObjectName("lineEdit_classifier")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_classifier)
        self.frame_dt = QtWidgets.QFrame(self.centralwidget)
        self.frame_dt.setGeometry(QtCore.QRect(20, 140, 211, 80))
        self.frame_dt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dt.setObjectName("frame_dt")
        self.layoutWidget = QtWidgets.QWidget(self.frame_dt)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 133, 69))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_dt = QtWidgets.QLabel(self.layoutWidget)
        self.label_dt.setObjectName("label_dt")
        self.verticalLayout.addWidget(self.label_dt)
        self.rbt_ar = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbt_ar.setObjectName("rbt_ar")
        self.verticalLayout.addWidget(self.rbt_ar)
        self.rbt_er = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbt_er.setObjectName("rbt_er")
        self.verticalLayout.addWidget(self.rbt_er)
        self.frame_plot = QtWidgets.QFrame(self.centralwidget)
        self.frame_plot.setGeometry(QtCore.QRect(230, 140, 231, 81))
        self.frame_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot.setObjectName("frame_plot")
        self.pbt_plot = QtWidgets.QPushButton(self.frame_plot)
        self.pbt_plot.setGeometry(QtCore.QRect(130, 50, 93, 28))
        self.pbt_plot.setObjectName("pbt_plot")
        self.pbt_clear = QtWidgets.QPushButton(self.frame_plot)
        self.pbt_clear.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pbt_clear.setObjectName("pbt_clear")
        self.line_h1 = QtWidgets.QFrame(self.centralwidget)
        self.line_h1.setGeometry(QtCore.QRect(20, 223, 441, 20))
        self.line_h1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h1.setObjectName("line_h1")
        self.label_des = QtWidgets.QLabel(self.centralwidget)
        self.label_des.setGeometry(QtCore.QRect(30, 240, 121, 21))
        self.label_des.setObjectName("label_des")
        self.textEdit_des = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_des.setGeometry(QtCore.QRect(20, 270, 441, 111))
        self.textEdit_des.setObjectName("textEdit_des")
        CcWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CcWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        CcWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CcWindow)
        self.statusbar.setObjectName("statusbar")
        CcWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(CcWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(CcWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionHTC_Homepage = QtWidgets.QAction(CcWindow)
        self.actionHTC_Homepage.setObjectName("actionHTC_Homepage")
        self.actionstyle_requirement = QtWidgets.QAction(CcWindow)
        self.actionstyle_requirement.setObjectName("actionstyle_requirement")
        self.menufile.addAction(self.actionopen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionexit)
        self.menuhelp.addAction(self.actionHTC_Homepage)
        self.menuhelp.addSeparator()
        self.menuhelp.addAction(self.actionstyle_requirement)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(CcWindow)
        QtCore.QMetaObject.connectSlotsByName(CcWindow)

    def retranslateUi(self, CcWindow):
        _translate = QtCore.QCoreApplication.translate
        CcWindow.setWindowTitle(_translate("CcWindow", "plot: classifier comparison"))
        self.pbt_input.setText(_translate("CcWindow", "Input:"))
        self.pbt_output.setText(_translate("CcWindow", "Output:"))
        self.label_classifier.setText(_translate("CcWindow", "Classifier:"))
        self.label_dt.setText(_translate("CcWindow", "Data Type:"))
        self.rbt_ar.setText(_translate("CcWindow", "accuracy rate"))
        self.rbt_er.setText(_translate("CcWindow", "error rate"))
        self.pbt_plot.setText(_translate("CcWindow", "plot"))
        self.pbt_clear.setText(_translate("CcWindow", "clear"))
        self.label_des.setText(_translate("CcWindow", "Descriptions:"))
        self.menufile.setTitle(_translate("CcWindow", "File"))
        self.menuhelp.setTitle(_translate("CcWindow", "Help"))
        self.actionopen.setText(_translate("CcWindow", "open"))
        self.actionexit.setText(_translate("CcWindow", "exit"))
        self.actionHTC_Homepage.setText(_translate("CcWindow", "HTC Homepage"))
        self.actionstyle_requirement.setText(_translate("CcWindow", "style requirements"))
