# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homepage.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HomepageWindow(object):
    def setupUi(self, HomepageWindow):
        HomepageWindow.setObjectName("HomepageWindow")
        HomepageWindow.setFixedSize(765, 700)
        self.centralwidget = QtWidgets.QWidget(HomepageWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_infor = QtWidgets.QFrame(self.centralwidget)
        self.frame_infor.setGeometry(QtCore.QRect(20, 460, 361, 161))
        self.frame_infor.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_infor.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_infor.setObjectName("frame_infor")
        self.line_v1 = QtWidgets.QFrame(self.frame_infor)
        self.line_v1.setGeometry(QtCore.QRect(-7, 10, 20, 141))
        self.line_v1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_v1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_v1.setObjectName("line_v1")
        self.widget = QtWidgets.QWidget(self.frame_infor)
        self.widget.setGeometry(QtCore.QRect(10, 10, 321, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout_infor = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_infor.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_infor.setObjectName("verticalLayout_infor")
        self.label_infor1 = QtWidgets.QLabel(self.widget)
        self.label_infor1.setObjectName("label_infor1")
        self.verticalLayout_infor.addWidget(self.label_infor1)
        self.label__infor2 = QtWidgets.QLabel(self.widget)
        self.label__infor2.setObjectName("label__infor2")
        self.verticalLayout_infor.addWidget(self.label__infor2)
        self.label__infor3 = QtWidgets.QLabel(self.widget)
        self.label__infor3.setObjectName("label__infor3")
        self.verticalLayout_infor.addWidget(self.label__infor3)
        self.label__infor4 = QtWidgets.QLabel(self.widget)
        self.label__infor4.setObjectName("label__infor4")
        self.verticalLayout_infor.addWidget(self.label__infor4)
        self.label__infor5 = QtWidgets.QLabel(self.widget)
        self.label__infor5.setObjectName("label__infor5")
        self.verticalLayout_infor.addWidget(self.label__infor5)
        self.label__infor6 = QtWidgets.QLabel(self.widget)
        self.label__infor6.setObjectName("label__infor6")
        self.verticalLayout_infor.addWidget(self.label__infor6)
        self.frame_image = QtWidgets.QFrame(self.centralwidget)
        self.frame_image.setGeometry(QtCore.QRect(20, 10, 401, 401))
        self.frame_image.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_image.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_image.setObjectName("frame_image")
        self.label_image = QtWidgets.QLabel(self.frame_image)
        self.label_image.setGeometry(QtCore.QRect(10, 80, 361, 311))
        self.label_image.setObjectName("label_image")
        self.frame_application = QtWidgets.QFrame(self.centralwidget)
        self.frame_application.setGeometry(QtCore.QRect(430, 10, 301, 621))
        self.frame_application.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_application.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_application.setObjectName("frame_application")
        self.label_application = QtWidgets.QLabel(self.frame_application)
        self.label_application.setGeometry(QtCore.QRect(20, 10, 111, 16))
        self.label_application.setObjectName("label_application")
        self.label_notice = QtWidgets.QLabel(self.frame_application)
        self.label_notice.setGeometry(QtCore.QRect(30, 420, 72, 15))
        self.label_notice.setObjectName("label_notice")
        self.pbt_ht = QtWidgets.QPushButton(self.frame_application)
        self.pbt_ht.setGeometry(QtCore.QRect(40, 50, 221, 51))
        self.pbt_ht.setObjectName("pbt_ht")
        self.pbt_plot = QtWidgets.QPushButton(self.frame_application)
        self.pbt_plot.setGeometry(QtCore.QRect(40, 120, 221, 51))
        self.pbt_plot.setObjectName("pbt_plot")
        self.pbt_dr = QtWidgets.QPushButton(self.frame_application)
        self.pbt_dr.setGeometry(QtCore.QRect(40, 190, 221, 51))
        self.pbt_dr.setObjectName("pbt_dr")
        self.pbt_knn = QtWidgets.QPushButton(self.frame_application)
        self.pbt_knn.setGeometry(QtCore.QRect(40, 260, 221, 51))
        self.pbt_knn.setObjectName("pbt_knn")
        self.pbt_ex = QtWidgets.QPushButton(self.frame_application)
        self.pbt_ex.setGeometry(QtCore.QRect(40, 330, 221, 51))
        self.pbt_ex.setObjectName("pbt_ex")
        self.line_v2 = QtWidgets.QFrame(self.frame_application)
        self.line_v2.setGeometry(QtCore.QRect(10, 40, 20, 361))
        self.line_v2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_v2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_v2.setObjectName("line_v2")
        self.line_v3 = QtWidgets.QFrame(self.frame_application)
        self.line_v3.setGeometry(QtCore.QRect(270, 40, 20, 361))
        self.line_v3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_v3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_v3.setObjectName("line_v3")
        self.line_h2 = QtWidgets.QFrame(self.frame_application)
        self.line_h2.setGeometry(QtCore.QRect(20, 390, 261, 20))
        self.line_h2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h2.setObjectName("line_h2")
        self.line_h1 = QtWidgets.QFrame(self.frame_application)
        self.line_h1.setGeometry(QtCore.QRect(20, 30, 261, 16))
        self.line_h1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h1.setObjectName("line_h1")
        self.textEdit_notice = QtWidgets.QTextEdit(self.frame_application)
        self.textEdit_notice.setGeometry(QtCore.QRect(20, 440, 261, 171))
        self.textEdit_notice.setObjectName("textEdit_notice")
        HomepageWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(HomepageWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 763, 26))
        self.menubar.setObjectName("menubar")
        self.menuProgram = QtWidgets.QMenu(self.menubar)
        self.menuProgram.setObjectName("menuProgram")
        self.menuVisualization = QtWidgets.QMenu(self.menubar)
        self.menuVisualization.setObjectName("menuVisualization")
        self.menubasic_model = QtWidgets.QMenu(self.menuVisualization)
        self.menubasic_model.setObjectName("menubasic_model")
        self.menuoverall_view = QtWidgets.QMenu(self.menubasic_model)
        self.menuoverall_view.setObjectName("menuoverall_view")
        self.menudimensionality_reduction = QtWidgets.QMenu(self.menuVisualization)
        self.menudimensionality_reduction.setObjectName("menudimensionality_reduction")
        self.menuHelps = QtWidgets.QMenu(self.menubar)
        self.menuHelps.setObjectName("menuHelps")
        HomepageWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(HomepageWindow)
        self.statusbar.setObjectName("statusbar")
        HomepageWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(HomepageWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(HomepageWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionkNN = QtWidgets.QAction(HomepageWindow)
        self.actionkNN.setObjectName("actionkNN")
        self.actionexit = QtWidgets.QAction(HomepageWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionAutoencoder = QtWidgets.QAction(HomepageWindow)
        self.actionAutoencoder.setObjectName("actionAutoencoder")
        self.actionLDA = QtWidgets.QAction(HomepageWindow)
        self.actionLDA.setObjectName("actionLDA")
        self.actionLE = QtWidgets.QAction(HomepageWindow)
        self.actionLE.setObjectName("actionLE")
        self.actionLPP = QtWidgets.QAction(HomepageWindow)
        self.actionLPP.setObjectName("actionLPP")
        self.actionMDS = QtWidgets.QAction(HomepageWindow)
        self.actionMDS.setObjectName("actionMDS")
        self.actionPCA = QtWidgets.QAction(HomepageWindow)
        self.actionPCA.setObjectName("actionPCA")
        self.actiont_SNE = QtWidgets.QAction(HomepageWindow)
        self.actiont_SNE.setObjectName("actiont_SNE")
        self.actioncritical_distance = QtWidgets.QAction(HomepageWindow)
        self.actioncritical_distance.setObjectName("actioncritical_distance")
        self.actionROC = QtWidgets.QAction(HomepageWindow)
        self.actionROC.setObjectName("actionROC")
        self.actionTexas_sharpshooter = QtWidgets.QAction(HomepageWindow)
        self.actionTexas_sharpshooter.setObjectName("actionTexas_sharpshooter")
        self.actionclassifiers_comparison = QtWidgets.QAction(HomepageWindow)
        self.actionclassifiers_comparison.setObjectName("actionclassifiers_comparison")
        self.actionHTC_homepage = QtWidgets.QAction(HomepageWindow)
        self.actionHTC_homepage.setObjectName("actionHTC_homepage")
        self.actiondata_file_format = QtWidgets.QAction(HomepageWindow)
        self.actiondata_file_format.setObjectName("actiondata_file_format")
        self.actiondataset_resource = QtWidgets.QAction(HomepageWindow)
        self.actiondataset_resource.setObjectName("actiondataset_resource")
        self.actionalgorithm_reference = QtWidgets.QAction(HomepageWindow)
        self.actionalgorithm_reference.setObjectName("actionalgorithm_reference")
        self.actioncheck_update = QtWidgets.QAction(HomepageWindow)
        self.actioncheck_update.setObjectName("actioncheck_update")
        self.actioncontact = QtWidgets.QAction(HomepageWindow)
        self.actioncontact.setObjectName("actioncontact")
        self.actionaccuracy_rate = QtWidgets.QAction(HomepageWindow)
        self.actionaccuracy_rate.setObjectName("actionaccuracy_rate")
        self.actionrunning_time = QtWidgets.QAction(HomepageWindow)
        self.actionrunning_time.setObjectName("actionrunning_time")
        self.menuProgram.addAction(self.actionopen)
        self.menuProgram.addAction(self.actionsave)
        self.menuProgram.addSeparator()
        self.menuProgram.addAction(self.actionkNN)
        self.menuProgram.addSeparator()
        self.menuProgram.addAction(self.actionexit)
        self.menuoverall_view.addAction(self.actionaccuracy_rate)
        self.menuoverall_view.addAction(self.actionrunning_time)
        self.menubasic_model.addAction(self.menuoverall_view.menuAction())
        self.menubasic_model.addSeparator()
        self.menubasic_model.addAction(self.actioncritical_distance)
        self.menubasic_model.addAction(self.actionROC)
        self.menubasic_model.addAction(self.actionTexas_sharpshooter)
        self.menubasic_model.addAction(self.actionclassifiers_comparison)
        self.menudimensionality_reduction.addAction(self.actionAutoencoder)
        self.menudimensionality_reduction.addAction(self.actionLDA)
        self.menudimensionality_reduction.addAction(self.actionLE)
        self.menudimensionality_reduction.addAction(self.actionLPP)
        self.menudimensionality_reduction.addAction(self.actionMDS)
        self.menudimensionality_reduction.addAction(self.actionPCA)
        self.menudimensionality_reduction.addAction(self.actiont_SNE)
        self.menuVisualization.addAction(self.menubasic_model.menuAction())
        self.menuVisualization.addAction(self.menudimensionality_reduction.menuAction())
        self.menuHelps.addAction(self.actionHTC_homepage)
        self.menuHelps.addSeparator()
        self.menuHelps.addAction(self.actiondata_file_format)
        self.menuHelps.addAction(self.actiondataset_resource)
        self.menuHelps.addAction(self.actionalgorithm_reference)
        self.menuHelps.addSeparator()
        self.menuHelps.addAction(self.actioncheck_update)
        self.menuHelps.addAction(self.actioncontact)
        self.menubar.addAction(self.menuProgram.menuAction())
        self.menubar.addAction(self.menuVisualization.menuAction())
        self.menubar.addAction(self.menuHelps.menuAction())

        self.retranslateUi(HomepageWindow)
        QtCore.QMetaObject.connectSlotsByName(HomepageWindow)

    def retranslateUi(self, HomepageWindow):
        _translate = QtCore.QCoreApplication.translate
        HomepageWindow.setWindowTitle(_translate("HomepageWindow", "Classification Hypothesis Testing GUI"))
        self.label_infor1.setText(_translate("HomepageWindow", "Classification Hypothesis Testing Tool"))
        self.label__infor2.setText(_translate("HomepageWindow", "Version 4.2.3"))
        self.label__infor3.setText(_translate("HomepageWindow", "(c) 2019 - 2020"))
        self.label__infor4.setText(_translate("HomepageWindow", "Beijing Jiaotong University"))
        self.label__infor5.setText(_translate("HomepageWindow", "Lancaster University"))
        self.label__infor6.setText(_translate("HomepageWindow", "Peng Song"))
        self.label_image.setText(_translate("HomepageWindow", "image"))
        self.label_application.setText(_translate("HomepageWindow", "HTCT_Application"))
        self.label_notice.setText(_translate("HomepageWindow", "Notice"))
        self.pbt_ht.setText(_translate("HomepageWindow", "Hypothesis Testing Model"))
        self.pbt_plot.setText(_translate("HomepageWindow", "General Evaluation Model"))
        self.pbt_dr.setText(_translate("HomepageWindow", "Dimensionality Reduction"))
        self.pbt_knn.setText(_translate("HomepageWindow", "kNN - Time Series"))
        self.pbt_ex.setText(_translate("HomepageWindow", "Expansion"))
        self.menuProgram.setTitle(_translate("HomepageWindow", "Program"))
        self.menuVisualization.setTitle(_translate("HomepageWindow", "Visualization"))
        self.menubasic_model.setTitle(_translate("HomepageWindow", "basic model"))
        self.menuoverall_view.setTitle(_translate("HomepageWindow", "overall_view"))
        self.menudimensionality_reduction.setTitle(_translate("HomepageWindow", "dimensionality reduction"))
        self.menuHelps.setTitle(_translate("HomepageWindow", "Helps"))
        self.actionopen.setText(_translate("HomepageWindow", "open"))
        self.actionsave.setText(_translate("HomepageWindow", "save"))
        self.actionkNN.setText(_translate("HomepageWindow", "kNN"))
        self.actionexit.setText(_translate("HomepageWindow", "exit"))
        self.actionAutoencoder.setText(_translate("HomepageWindow", "Autoencoder"))
        self.actionLDA.setText(_translate("HomepageWindow", "LDA"))
        self.actionLE.setText(_translate("HomepageWindow", "LE"))
        self.actionLPP.setText(_translate("HomepageWindow", "LPP"))
        self.actionMDS.setText(_translate("HomepageWindow", "MDS"))
        self.actionPCA.setText(_translate("HomepageWindow", "PCA"))
        self.actiont_SNE.setText(_translate("HomepageWindow", "t-SNE"))
        self.actioncritical_distance.setText(_translate("HomepageWindow", "critical distance"))
        self.actionROC.setText(_translate("HomepageWindow", "ROC"))
        self.actionTexas_sharpshooter.setText(_translate("HomepageWindow", "Texas sharpshooter"))
        self.actionclassifiers_comparison.setText(_translate("HomepageWindow", "classifiers comparison"))
        self.actionHTC_homepage.setText(_translate("HomepageWindow", "HTC homepage"))
        self.actiondata_file_format.setText(_translate("HomepageWindow", "data file format"))
        self.actiondataset_resource.setText(_translate("HomepageWindow", "dataset resource"))
        self.actionalgorithm_reference.setText(_translate("HomepageWindow", "algorithm reference"))
        self.actioncheck_update.setText(_translate("HomepageWindow", "check update"))
        self.actioncontact.setText(_translate("HomepageWindow", "contact"))
        self.actionaccuracy_rate.setText(_translate("HomepageWindow", "accuracy rate"))
        self.actionrunning_time.setText(_translate("HomepageWindow", "running time"))
