# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ht.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HtWindow(object):
    def setupUi(self, HtWindow):
        HtWindow.setObjectName("HtWindow")
        HtWindow.setFixedSize(810, 500)
        self.centralwidget = QtWidgets.QWidget(HtWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_fp = QtWidgets.QLabel(self.centralwidget)
        self.label_fp.setGeometry(QtCore.QRect(37, 30, 81, 15))
        self.label_fp.setObjectName("label_fp")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 30, 311, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.frame_ht = QtWidgets.QFrame(self.centralwidget)
        self.frame_ht.setGeometry(QtCore.QRect(20, 180, 411, 261))
        self.frame_ht.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_ht.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_ht.setObjectName("frame_ht")
        self.label_paired = QtWidgets.QLabel(self.frame_ht)
        self.label_paired.setGeometry(QtCore.QRect(10, 10, 161, 16))
        self.label_paired.setObjectName("label_paired")
        self.line_h1 = QtWidgets.QFrame(self.frame_ht)
        self.line_h1.setGeometry(QtCore.QRect(10, 20, 151, 16))
        self.line_h1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h1.setObjectName("line_h1")
        self.layoutWidget = QtWidgets.QWidget(self.frame_ht)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 30, 171, 221))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_paired = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_paired.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_paired.setObjectName("gridLayout_paired")
        self.pbt_mn = QtWidgets.QPushButton(self.layoutWidget)
        self.pbt_mn.setObjectName("pbt_mn")
        self.gridLayout_paired.addWidget(self.pbt_mn, 4, 0, 1, 1)
        self.pbt_pt = QtWidgets.QPushButton(self.layoutWidget)
        self.pbt_pt.setObjectName("pbt_pt")
        self.gridLayout_paired.addWidget(self.pbt_pt, 1, 0, 1, 1)
        self.pbt_mw = QtWidgets.QPushButton(self.layoutWidget)
        self.pbt_mw.setObjectName("pbt_mw")
        self.gridLayout_paired.addWidget(self.pbt_mw, 5, 0, 1, 1)
        self.pbt_w = QtWidgets.QPushButton(self.layoutWidget)
        self.pbt_w.setObjectName("pbt_w")
        self.gridLayout_paired.addWidget(self.pbt_w, 3, 0, 1, 1)
        self.pbt_rs = QtWidgets.QPushButton(self.layoutWidget)
        self.pbt_rs.setObjectName("pbt_rs")
        self.gridLayout_paired.addWidget(self.pbt_rs, 2, 0, 1, 1)
        self.label_multiple = QtWidgets.QLabel(self.frame_ht)
        self.label_multiple.setGeometry(QtCore.QRect(220, 10, 181, 16))
        self.label_multiple.setObjectName("label_multiple")
        self.line_h2 = QtWidgets.QFrame(self.frame_ht)
        self.line_h2.setGeometry(QtCore.QRect(230, 20, 161, 16))
        self.line_h2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h2.setObjectName("line_h2")
        self.layoutWidget1 = QtWidgets.QWidget(self.frame_ht)
        self.layoutWidget1.setGeometry(QtCore.QRect(220, 30, 171, 141))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_multiple = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_multiple.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_multiple.setObjectName("gridLayout_multiple")
        self.pbt_va = QtWidgets.QPushButton(self.layoutWidget1)
        self.pbt_va.setObjectName("pbt_va")
        self.gridLayout_multiple.addWidget(self.pbt_va, 1, 0, 1, 1)
        self.pbt_kr = QtWidgets.QPushButton(self.layoutWidget1)
        self.pbt_kr.setObjectName("pbt_kr")
        self.gridLayout_multiple.addWidget(self.pbt_kr, 2, 0, 1, 1)
        self.pbt_fr = QtWidgets.QPushButton(self.layoutWidget1)
        self.pbt_fr.setObjectName("pbt_fr")
        self.gridLayout_multiple.addWidget(self.pbt_fr, 0, 0, 1, 1)
        self.line_v1 = QtWidgets.QFrame(self.frame_ht)
        self.line_v1.setGeometry(QtCore.QRect(190, 0, 20, 261))
        self.line_v1.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_v1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_v1.setObjectName("line_v1")
        self.line_h1_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_h1_2.setGeometry(QtCore.QRect(30, 170, 401, 16))
        self.line_h1_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h1_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h1_2.setObjectName("line_h1_2")
        self.frame_dt = QtWidgets.QFrame(self.centralwidget)
        self.frame_dt.setGeometry(QtCore.QRect(30, 60, 151, 101))
        self.frame_dt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dt.setObjectName("frame_dt")
        self.layoutWidget2 = QtWidgets.QWidget(self.frame_dt)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 133, 81))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_dt = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_dt.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_dt.setObjectName("verticalLayout_dt")
        self.label_dt = QtWidgets.QLabel(self.layoutWidget2)
        self.label_dt.setObjectName("label_dt")
        self.verticalLayout_dt.addWidget(self.label_dt)
        self.rbt_er = QtWidgets.QRadioButton(self.layoutWidget2)
        self.rbt_er.setObjectName("rbt_er")
        self.verticalLayout_dt.addWidget(self.rbt_er)
        self.rbt_ar = QtWidgets.QRadioButton(self.layoutWidget2)
        self.rbt_ar.setObjectName("rbt_ar")
        self.verticalLayout_dt.addWidget(self.rbt_ar)
        self.frame_con = QtWidgets.QFrame(self.centralwidget)
        self.frame_con.setGeometry(QtCore.QRect(180, 60, 141, 101))
        self.frame_con.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_con.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_con.setObjectName("frame_con")
        self.layoutWidget3 = QtWidgets.QWidget(self.frame_con)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 10, 117, 81))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_con = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_con.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_con.setObjectName("verticalLayout_con")
        self.label_con = QtWidgets.QLabel(self.layoutWidget3)
        self.label_con.setObjectName("label_con")
        self.verticalLayout_con.addWidget(self.label_con)
        self.rbt_005 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.rbt_005.setObjectName("rbt_005")
        self.verticalLayout_con.addWidget(self.rbt_005)
        self.rbt_01 = QtWidgets.QRadioButton(self.layoutWidget3)
        self.rbt_01.setObjectName("rbt_01")
        self.verticalLayout_con.addWidget(self.rbt_01)
        self.line_v2 = QtWidgets.QFrame(self.centralwidget)
        self.line_v2.setGeometry(QtCore.QRect(422, 20, 60, 421))
        self.line_v2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_v2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_v2.setObjectName("line_v2")
        self.frame_tr = QtWidgets.QFrame(self.centralwidget)
        self.frame_tr.setGeometry(QtCore.QRect(460, 20, 331, 421))
        self.frame_tr.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_tr.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_tr.setObjectName("frame_tr")
        self.label_tr = QtWidgets.QLabel(self.frame_tr)
        self.label_tr.setGeometry(QtCore.QRect(10, 10, 131, 21))
        self.label_tr.setObjectName("label_tr")
        self.textEdit_result = QtWidgets.QTextEdit(self.frame_tr)
        self.textEdit_result.setGeometry(QtCore.QRect(10, 40, 301, 331))
        self.textEdit_result.setObjectName("textEdit_result")
        self.pbt_clear = QtWidgets.QPushButton(self.frame_tr)
        self.pbt_clear.setGeometry(QtCore.QRect(220, 390, 93, 28))
        self.pbt_clear.setObjectName("pbt_clear")
        HtWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(HtWindow)
        self.statusbar.setObjectName("statusbar")
        HtWindow.setStatusBar(self.statusbar)
        self.menuBar = QtWidgets.QMenuBar(HtWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 812, 26))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        HtWindow.setMenuBar(self.menuBar)
        self.actionopen = QtWidgets.QAction(HtWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(HtWindow)
        self.actionexit.setObjectName("actionexit")
        self.menuFile.addAction(self.actionopen)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionexit)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(HtWindow)
        QtCore.QMetaObject.connectSlotsByName(HtWindow)

    def retranslateUi(self, HtWindow):
        _translate = QtCore.QCoreApplication.translate
        HtWindow.setWindowTitle(_translate("HtWindow", "hypothesis testing"))
        self.label_fp.setText(_translate("HtWindow", "File Path:"))
        self.label_paired.setText(_translate("HtWindow", "Paired Classifiers:"))
        self.pbt_mn.setText(_translate("HtWindow", "McNemar"))
        self.pbt_pt.setText(_translate("HtWindow", "Paired T"))
        self.pbt_mw.setText(_translate("HtWindow", "Mann-Whitneyu"))
        self.pbt_w.setText(_translate("HtWindow", "Wilcoxon"))
        self.pbt_rs.setText(_translate("HtWindow", "Rank Sums"))
        self.label_multiple.setText(_translate("HtWindow", "Multiple Classifiers:"))
        self.pbt_va.setText(_translate("HtWindow", "Variance Analysis"))
        self.pbt_kr.setText(_translate("HtWindow", "Kruskal"))
        self.pbt_fr.setText(_translate("HtWindow", "Friedman"))
        self.label_dt.setText(_translate("HtWindow", "Data Type:"))
        self.rbt_er.setText(_translate("HtWindow", "error rate"))
        self.rbt_ar.setText(_translate("HtWindow", "accuracy rate"))
        self.label_con.setText(_translate("HtWindow", "Confidence:"))
        self.rbt_005.setText(_translate("HtWindow", "0.05"))
        self.rbt_01.setText(_translate("HtWindow", "0.1"))
        self.label_tr.setText(_translate("HtWindow", "Testing Result: "))
        self.pbt_clear.setText(_translate("HtWindow", "clear"))
        self.menuFile.setTitle(_translate("HtWindow", "File"))
        self.actionopen.setText(_translate("HtWindow", "open"))
        self.actionexit.setText(_translate("HtWindow", "exit"))
