# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'knn.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_KNNWindow(object):
    def setupUi(self, KNNWindow):
        KNNWindow.setObjectName("KNNWindow")
        KNNWindow.setFixedSize(570, 730)
        self.centralwidget = QtWidgets.QWidget(KNNWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_file = QtWidgets.QFrame(self.centralwidget)
        self.frame_file.setGeometry(QtCore.QRect(20, 10, 531, 431))
        self.frame_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file.setObjectName("frame_file")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_file)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 501, 141))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout_file = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout_file.setContentsMargins(0, 0, 0, 0)
        self.formLayout_file.setObjectName("formLayout_file")
        self.pbt_train = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_train.setObjectName("pbt_train")
        self.formLayout_file.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pbt_train)
        self.lineEdit_train = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_train.setObjectName("lineEdit_train")
        self.formLayout_file.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_train)
        self.pbt_test = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_test.setObjectName("pbt_test")
        self.formLayout_file.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pbt_test)
        self.lineEdit_test = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_test.setObjectName("lineEdit_test")
        self.formLayout_file.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_test)
        self.label_k = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_k.setObjectName("label_k")
        self.formLayout_file.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_k)
        self.comboBox_k = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_k.setObjectName("comboBox_k")
        self.comboBox_k.addItem("")
        self.comboBox_k.addItem("")
        self.comboBox_k.addItem("")
        self.comboBox_k.addItem("")
        self.comboBox_k.addItem("")
        self.formLayout_file.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_k)
        self.label_dt = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_dt.setObjectName("label_dt")
        self.formLayout_file.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_dt)
        self.comboBox_dt = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_dt.setObjectName("comboBox_dt")
        self.comboBox_dt.addItem("")
        self.comboBox_dt.addItem("")
        self.comboBox_dt.addItem("")
        self.comboBox_dt.addItem("")
        self.comboBox_dt.addItem("")
        self.comboBox_dt.addItem("")
        self.comboBox_dt.addItem("")
        self.comboBox_dt.addItem("")
        self.formLayout_file.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_dt)
        self.pbt_clear = QtWidgets.QPushButton(self.frame_file)
        self.pbt_clear.setGeometry(QtCore.QRect(310, 160, 93, 28))
        self.pbt_clear.setObjectName("pbt_clear")
        self.pbt_start = QtWidgets.QPushButton(self.frame_file)
        self.pbt_start.setGeometry(QtCore.QRect(420, 160, 93, 28))
        self.pbt_start.setObjectName("pbt_start")
        self.line_h1 = QtWidgets.QFrame(self.frame_file)
        self.line_h1.setGeometry(QtCore.QRect(10, 190, 501, 20))
        self.line_h1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h1.setObjectName("line_h1")
        self.label_result = QtWidgets.QLabel(self.frame_file)
        self.label_result.setGeometry(QtCore.QRect(10, 210, 72, 15))
        self.label_result.setObjectName("label_result")
        self.textEdit_result = QtWidgets.QTextEdit(self.frame_file)
        self.textEdit_result.setGeometry(QtCore.QRect(10, 230, 501, 171))
        self.textEdit_result.setObjectName("textEdit_result")
        self.line_h2 = QtWidgets.QFrame(self.frame_file)
        self.line_h2.setGeometry(QtCore.QRect(10, 420, 501, 16))
        self.line_h2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h2.setObjectName("line_h2")
        self.frame_des = QtWidgets.QFrame(self.centralwidget)
        self.frame_des.setGeometry(QtCore.QRect(20, 440, 531, 221))
        self.frame_des.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_des.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_des.setObjectName("frame_des")
        self.textEdit_des = QtWidgets.QTextEdit(self.frame_des)
        self.textEdit_des.setGeometry(QtCore.QRect(10, 40, 501, 171))
        self.textEdit_des.setObjectName("textEdit_des")
        self.label_des = QtWidgets.QLabel(self.frame_des)
        self.label_des.setGeometry(QtCore.QRect(10, 10, 121, 21))
        self.label_des.setObjectName("label_des")
        KNNWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KNNWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 567, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuopen = QtWidgets.QMenu(self.menufile)
        self.menuopen.setObjectName("menuopen")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        KNNWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(KNNWindow)
        self.statusbar.setObjectName("statusbar")
        KNNWindow.setStatusBar(self.statusbar)
        self.actionexit = QtWidgets.QAction(KNNWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionHTC_Homepage = QtWidgets.QAction(KNNWindow)
        self.actionHTC_Homepage.setObjectName("actionHTC_Homepage")
        self.actionstyle_requirement = QtWidgets.QAction(KNNWindow)
        self.actionstyle_requirement.setObjectName("actionstyle_requirement")
        self.actiontrain_dataset = QtWidgets.QAction(KNNWindow)
        self.actiontrain_dataset.setObjectName("actiontrain_dataset")
        self.actiontest_dataset = QtWidgets.QAction(KNNWindow)
        self.actiontest_dataset.setObjectName("actiontest_dataset")
        self.menuopen.addAction(self.actiontrain_dataset)
        self.menuopen.addAction(self.actiontest_dataset)
        self.menufile.addAction(self.menuopen.menuAction())
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionexit)
        self.menuhelp.addAction(self.actionHTC_Homepage)
        self.menuhelp.addSeparator()
        self.menuhelp.addAction(self.actionstyle_requirement)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(KNNWindow)
        QtCore.QMetaObject.connectSlotsByName(KNNWindow)

    def retranslateUi(self, KNNWindow):
        _translate = QtCore.QCoreApplication.translate
        KNNWindow.setWindowTitle(_translate("KNNWindow", "kNN"))
        self.pbt_train.setText(_translate("KNNWindow", "Train Dataset:"))
        self.pbt_test.setText(_translate("KNNWindow", "Test Dataset: "))
        self.label_k.setText(_translate("KNNWindow", "K Value:"))
        self.comboBox_k.setItemText(0, _translate("KNNWindow", "1"))
        self.comboBox_k.setItemText(1, _translate("KNNWindow", "2"))
        self.comboBox_k.setItemText(2, _translate("KNNWindow", "3"))
        self.comboBox_k.setItemText(3, _translate("KNNWindow", "4"))
        self.comboBox_k.setItemText(4, _translate("KNNWindow", "5"))
        self.label_dt.setText(_translate("KNNWindow", "Distance Type:"))
        self.comboBox_dt.setItemText(0, _translate("KNNWindow", "Euclidean Distance"))
        self.comboBox_dt.setItemText(1, _translate("KNNWindow", "fast DTW"))
        self.comboBox_dt.setItemText(2, _translate("KNNWindow", "Pearson"))
        self.comboBox_dt.setItemText(3, _translate("KNNWindow", "SAX"))
        self.comboBox_dt.setItemText(4, _translate("KNNWindow", "Complexity-Invariant Distance, CID (uncompleted)"))
        self.comboBox_dt.setItemText(5, _translate("KNNWindow", "Uniform Scaling, US (uncompleted)"))
        self.comboBox_dt.setItemText(6, _translate("KNNWindow", "PAA (uncompleted)"))
        self.comboBox_dt.setItemText(7, _translate("KNNWindow", "Longest Common Sequence, LCS (uncompleted)"))
        self.pbt_clear.setText(_translate("KNNWindow", "clear"))
        self.pbt_start.setText(_translate("KNNWindow", "start"))
        self.label_result.setText(_translate("KNNWindow", "Result"))
        self.label_des.setText(_translate("KNNWindow", "Descriptions"))
        self.menufile.setTitle(_translate("KNNWindow", "File"))
        self.menuopen.setTitle(_translate("KNNWindow", "open"))
        self.menuhelp.setTitle(_translate("KNNWindow", "Help"))
        self.actionexit.setText(_translate("KNNWindow", "exit"))
        self.actionHTC_Homepage.setText(_translate("KNNWindow", "HTC Homepage"))
        self.actionstyle_requirement.setText(_translate("KNNWindow", "style requirements"))
        self.actiontrain_dataset.setText(_translate("KNNWindow", "train dataset"))
        self.actiontest_dataset.setText(_translate("KNNWindow", "test dataset"))
