# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'roc.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RocWindow(object):
    def setupUi(self, CdWindow):
        CdWindow.setObjectName("CdWindow")
        CdWindow.setFixedSize(485, 430)
        self.centralwidget = QtWidgets.QWidget(CdWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_file = QtWidgets.QFrame(self.centralwidget)
        self.frame_file.setGeometry(QtCore.QRect(20, 10, 441, 141))
        self.frame_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file.setObjectName("frame_file")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_file)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 421, 111))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.lineEdit_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_input)
        self.lineEdit_output = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_output)
        self.pbt_input = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_input.setObjectName("pbt_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pbt_input)
        self.pbt_output = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_output.setObjectName("pbt_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pbt_output)
        self.label_pl = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_pl.setObjectName("label_pl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_pl)
        self.lineEdit_pl = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_pl.setObjectName("lineEdit_pl")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_pl)
        self.frame_plot = QtWidgets.QFrame(self.centralwidget)
        self.frame_plot.setGeometry(QtCore.QRect(240, 160, 231, 41))
        self.frame_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot.setObjectName("frame_plot")
        self.pbt_plot = QtWidgets.QPushButton(self.frame_plot)
        self.pbt_plot.setGeometry(QtCore.QRect(120, 0, 93, 28))
        self.pbt_plot.setObjectName("pbt_plot")
        self.pbt_clear = QtWidgets.QPushButton(self.frame_plot)
        self.pbt_clear.setGeometry(QtCore.QRect(10, 0, 93, 28))
        self.pbt_clear.setObjectName("pbt_clear")
        self.line_h1 = QtWidgets.QFrame(self.centralwidget)
        self.line_h1.setGeometry(QtCore.QRect(20, 203, 441, 20))
        self.line_h1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h1.setObjectName("line_h1")
        self.label_des = QtWidgets.QLabel(self.centralwidget)
        self.label_des.setGeometry(QtCore.QRect(30, 220, 121, 21))
        self.label_des.setObjectName("label_des")
        self.textEdit_des = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_des.setGeometry(QtCore.QRect(20, 250, 441, 111))
        self.textEdit_des.setObjectName("textEdit_des")
        CdWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(CdWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        CdWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(CdWindow)
        self.statusbar.setObjectName("statusbar")
        CdWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(CdWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(CdWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionHTC_Homepage = QtWidgets.QAction(CdWindow)
        self.actionHTC_Homepage.setObjectName("actionHTC_Homepage")
        self.actionstyle_requirement = QtWidgets.QAction(CdWindow)
        self.actionstyle_requirement.setObjectName("actionstyle_requirement")
        self.menufile.addAction(self.actionopen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionexit)
        self.menuhelp.addAction(self.actionHTC_Homepage)
        self.menuhelp.addSeparator()
        self.menuhelp.addAction(self.actionstyle_requirement)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(CdWindow)
        QtCore.QMetaObject.connectSlotsByName(CdWindow)

    def retranslateUi(self, CdWindow):
        _translate = QtCore.QCoreApplication.translate
        CdWindow.setWindowTitle(_translate("CdWindow", "plot: ROC"))
        self.pbt_input.setText(_translate("CdWindow", "Input:"))
        self.pbt_output.setText(_translate("CdWindow", "Output:"))
        self.label_pl.setText(_translate("CdWindow", "Positive Label:"))
        self.pbt_plot.setText(_translate("CdWindow", "plot"))
        self.pbt_clear.setText(_translate("CdWindow", "clear"))
        self.label_des.setText(_translate("CdWindow", "Descriptions:"))
        self.menufile.setTitle(_translate("CdWindow", "File"))
        self.menuhelp.setTitle(_translate("CdWindow", "Help"))
        self.actionopen.setText(_translate("CdWindow", "open"))
        self.actionexit.setText(_translate("CdWindow", "exit"))
        self.actionHTC_Homepage.setText(_translate("CdWindow", "HTC Homepage"))
        self.actionstyle_requirement.setText(_translate("CdWindow", "style requirements"))
