# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tss.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TssWindow(object):
    def setupUi(self, TssWindow):
        TssWindow.setObjectName("TssWindow")
        TssWindow.setFixedSize(485, 470)
        self.centralwidget = QtWidgets.QWidget(TssWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_file = QtWidgets.QFrame(self.centralwidget)
        self.frame_file.setGeometry(QtCore.QRect(20, 10, 441, 141))
        self.frame_file.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_file.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_file.setObjectName("frame_file")
        self.formLayoutWidget = QtWidgets.QWidget(self.frame_file)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 421, 71))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.pbt_input = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_input.setObjectName("pbt_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.pbt_input)
        self.lineEdit_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_input.setObjectName("lineEdit_input")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_input)
        self.pbt_output = QtWidgets.QPushButton(self.formLayoutWidget)
        self.pbt_output.setObjectName("pbt_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.pbt_output)
        self.lineEdit_output = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_output.setObjectName("lineEdit_output")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_output)
        self.gridLayoutWidget = QtWidgets.QWidget(self.frame_file)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 421, 41))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout_classifier = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_classifier.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_classifier.setObjectName("gridLayout_classifier")
        self.lineEdit_ca = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_ca.setObjectName("lineEdit_ca")
        self.gridLayout_classifier.addWidget(self.lineEdit_ca, 0, 1, 1, 1)
        self.label_ca = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_ca.setObjectName("label_ca")
        self.gridLayout_classifier.addWidget(self.label_ca, 0, 0, 1, 1)
        self.lineEdit_cb = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_cb.setObjectName("lineEdit_cb")
        self.gridLayout_classifier.addWidget(self.lineEdit_cb, 0, 3, 1, 1)
        self.label_cb = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_cb.setObjectName("label_cb")
        self.gridLayout_classifier.addWidget(self.label_cb, 0, 2, 1, 1)
        self.frame_dt = QtWidgets.QFrame(self.centralwidget)
        self.frame_dt.setGeometry(QtCore.QRect(20, 150, 171, 80))
        self.frame_dt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_dt.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_dt.setObjectName("frame_dt")
        self.layoutWidget = QtWidgets.QWidget(self.frame_dt)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 133, 69))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_dt = QtWidgets.QLabel(self.layoutWidget)
        self.label_dt.setObjectName("label_dt")
        self.verticalLayout.addWidget(self.label_dt)
        self.rbt_ar = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbt_ar.setObjectName("rbt_ar")
        self.verticalLayout.addWidget(self.rbt_ar)
        self.rbt_er = QtWidgets.QRadioButton(self.layoutWidget)
        self.rbt_er.setObjectName("rbt_er")
        self.verticalLayout.addWidget(self.rbt_er)
        self.frame_plot = QtWidgets.QFrame(self.centralwidget)
        self.frame_plot.setGeometry(QtCore.QRect(230, 150, 231, 81))
        self.frame_plot.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_plot.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_plot.setObjectName("frame_plot")
        self.pbt_plot = QtWidgets.QPushButton(self.frame_plot)
        self.pbt_plot.setGeometry(QtCore.QRect(130, 50, 93, 28))
        self.pbt_plot.setObjectName("pbt_plot")
        self.pbt_clear = QtWidgets.QPushButton(self.frame_plot)
        self.pbt_clear.setGeometry(QtCore.QRect(10, 50, 93, 28))
        self.pbt_clear.setObjectName("pbt_clear")
        self.line_h1 = QtWidgets.QFrame(self.centralwidget)
        self.line_h1.setGeometry(QtCore.QRect(20, 233, 441, 20))
        self.line_h1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_h1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_h1.setObjectName("line_h1")
        self.label_des = QtWidgets.QLabel(self.centralwidget)
        self.label_des.setGeometry(QtCore.QRect(30, 250, 121, 21))
        self.label_des.setObjectName("label_des")
        self.textEdit_des = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_des.setGeometry(QtCore.QRect(20, 280, 441, 111))
        self.textEdit_des.setObjectName("textEdit_des")
        TssWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(TssWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 26))
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setObjectName("menufile")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        TssWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(TssWindow)
        self.statusbar.setObjectName("statusbar")
        TssWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(TssWindow)
        self.actionopen.setObjectName("actionopen")
        self.actionexit = QtWidgets.QAction(TssWindow)
        self.actionexit.setObjectName("actionexit")
        self.actionHTC_Homepage = QtWidgets.QAction(TssWindow)
        self.actionHTC_Homepage.setObjectName("actionHTC_Homepage")
        self.actionstyle_requirement = QtWidgets.QAction(TssWindow)
        self.actionstyle_requirement.setObjectName("actionstyle_requirement")
        self.menufile.addAction(self.actionopen)
        self.menufile.addSeparator()
        self.menufile.addAction(self.actionexit)
        self.menuhelp.addAction(self.actionHTC_Homepage)
        self.menuhelp.addSeparator()
        self.menuhelp.addAction(self.actionstyle_requirement)
        self.menubar.addAction(self.menufile.menuAction())
        self.menubar.addAction(self.menuhelp.menuAction())

        self.retranslateUi(TssWindow)
        QtCore.QMetaObject.connectSlotsByName(TssWindow)

    def retranslateUi(self, TssWindow):
        _translate = QtCore.QCoreApplication.translate
        TssWindow.setWindowTitle(_translate("TssWindow", "plot: Texas Sharpshooter"))
        self.pbt_input.setText(_translate("TssWindow", "Input:"))
        self.pbt_output.setText(_translate("TssWindow", "Output:"))
        self.label_ca.setText(_translate("TssWindow", "Classifier A:"))
        self.label_cb.setText(_translate("TssWindow", "Classifier B:"))
        self.label_dt.setText(_translate("TssWindow", "Data Type:"))
        self.rbt_ar.setText(_translate("TssWindow", "accuracy rate"))
        self.rbt_er.setText(_translate("TssWindow", "error rate"))
        self.pbt_plot.setText(_translate("TssWindow", "plot"))
        self.pbt_clear.setText(_translate("TssWindow", "clear"))
        self.label_des.setText(_translate("TssWindow", "Descriptions:"))
        self.menufile.setTitle(_translate("TssWindow", "File"))
        self.menuhelp.setTitle(_translate("TssWindow", "Help"))
        self.actionopen.setText(_translate("TssWindow", "open"))
        self.actionexit.setText(_translate("TssWindow", "exit"))
        self.actionHTC_Homepage.setText(_translate("TssWindow", "HTC Homepage"))
        self.actionstyle_requirement.setText(_translate("TssWindow", "style requirements"))
